### ISSUE TITLE
addTrack

### ISSUE THREAD

**Issue by cyr3ne** [angelvinyals/Jammming#2]
https://github.com/angelvinyals/Jammming/blob/29fe52369cd23e8bf984878789ff37876297b6c5/src/components/App/App.js#L37-L47

Interesting implementation of the addTrack method. I like looking at the add track methods because I have seen a hundred different ways to make this method. It's interesting to see. Here is another version.

**Comment by angelvinyals** [comment]
new es6 spread operator  is awesome.
