### ISSUE TITLE
Spotify routing

### ISSUE THREAD

**Issue by cyr3ne** [angelvinyals/Jammming#3]
https://github.com/angelvinyals/Jammming/blob/29fe52369cd23e8bf984878789ff37876297b6c5/src/util/Spotify.js#L2

Why do you have this call back thing? I haven't seen that before

**Comment by angelvinyals** [comment]
as it says here: [https://developer.spotify.com/web-api/authorization-guide/#implicit-grant-flo](url) .

> 3. The user is redirected back to your specified URI
> After the user grants (or denies) access, the Spotify Accounts service redirects the user to the redirect_uri.... 
If the user has granted access, the final URL will contain a hash fragment with the following data encoded as a query string:
